"""Quadrotor benchmark of Sun et al., "A Comparative Study of Nonlinear MPC and
Differential-Flatness-Based Control for Quadrotor Agile Flight", IEEE T-RO 2022
(https://arxiv.org/abs/2109.01365).

The NMPC of that study tracks elliptical trajectories at up to 20 m/s with the
single rotor thrusts as inputs, bounded by the real thrust limits of the
platform. Many of the references are dynamically infeasible: flying them would
need more thrust than the rotors can deliver, so the bounds are active for most
of the flight. Model, parameters and controller weights are those of the paper
(Sec. III-B, Tables I and II).
"""
import numpy as np
from examples.python.utils import rk4

nx = 13     # position, velocity, attitude quaternion, body rate
nu = 4      # single rotor thrusts

g = 9.81
mass = 0.75                                 # kg
Iv = np.array([2.5e-3, 2.1e-3, 4.3e-3])     # kg m^2
l = 0.14                                    # m
beta = np.radians(56)                       # rotor arm angle
u_min = 0.0                                 # N, per rotor
u_max = 8.5                                 # N, per rotor
ct = 1.51e-6                                # N s^2
cq = 2.37e-8                                # N m s^2
kd = np.array([0.26, 0.28, 0.42])           # kg/s, aerodynamic drag
kh = 0.01                                   # kg/m

# Collective thrust and body torque generated by the four rotor thrusts.
G1 = np.array([[1., 1., 1., 1.],
               [l*np.sin(beta), -l*np.sin(beta), -l*np.sin(beta), l*np.sin(beta)],
               [-l*np.cos(beta), -l*np.cos(beta), l*np.cos(beta), l*np.cos(beta)],
               [cq/ct, -cq/ct, cq/ct, -cq/ct]])

N = 20                  # optimization nodes
Ts = 0.05               # s, node spacing (horizon of 1 s)
control_dt = 0.01       # s, the NMPC runs at 100 Hz
sim_dt = 0.002          # s, the simulation propagates the model at 500 Hz

# Cost of the optimal control problem, Table I.
Qp = np.array([200., 200., 500.])       # position
Qv = np.array([1., 1., 1.])             # velocity
Qq = np.array([5., 5., 200.])           # attitude, on the quaternion error
Qw = np.array([1., 1., 1.])             # body rate
Qu = np.full(nu, 6.)                    # rotor thrusts
# The paper constrains the body rates but does not publish the bounds.
w_max = np.full(3, 10.0)                # rad/s

def q_to_rot(q):
    """Rotation matrix of a quaternion, in the form that stays exact when the
    quaternion is not normalized, as it is inside an integration step."""
    qw, qx, qy, qz = q
    return np.array([
        [qw**2 + qx**2 - qy**2 - qz**2, 2*(qx*qy - qw*qz), 2*(qx*qz + qw*qy)],
        [2*(qx*qy + qw*qz), qw**2 - qx**2 + qy**2 - qz**2, 2*(qy*qz - qw*qx)],
        [2*(qx*qz - qw*qy), 2*(qy*qz + qw*qx), qw**2 - qx**2 - qy**2 + qz**2]])

def q_mult(q, p):
    qw, qx, qy, qz = q
    pw, px, py, pz = p
    return np.array([qw*pw - qx*px - qy*py - qz*pz,
                     qw*px + qx*pw + qy*pz - qz*py,
                     qw*py - qx*pz + qy*pw + qz*px,
                     qw*pz + qx*py - qy*px + qz*pw])

q_conj = lambda q: np.array([q[0], -q[1], -q[2], -q[3]])
unit_q = lambda q: q / np.linalg.norm(q)

def rot_to_q(R):
    """Quaternion of a rotation matrix, branching on its largest component."""
    trace = np.trace(R)
    if trace > 0:
        s = 2 * np.sqrt(1 + trace)
        q = [0.25*s, (R[2,1] - R[1,2])/s, (R[0,2] - R[2,0])/s, (R[1,0] - R[0,1])/s]
    elif R[0,0] > R[1,1] and R[0,0] > R[2,2]:
        s = 2 * np.sqrt(1 + R[0,0] - R[1,1] - R[2,2])
        q = [(R[2,1] - R[1,2])/s, 0.25*s, (R[0,1] + R[1,0])/s, (R[0,2] + R[2,0])/s]
    elif R[1,1] > R[2,2]:
        s = 2 * np.sqrt(1 + R[1,1] - R[0,0] - R[2,2])
        q = [(R[0,2] - R[2,0])/s, (R[0,1] + R[1,0])/s, 0.25*s, (R[1,2] + R[2,1])/s]
    else:
        s = 2 * np.sqrt(1 + R[2,2] - R[0,0] - R[1,1])
        q = [(R[1,0] - R[0,1])/s, (R[0,2] + R[2,0])/s, (R[1,2] + R[2,1])/s, 0.25*s]
    return unit_q(np.array(q))

def q_error_jacobian(q_r):
    """Jacobian of the attitude error q * q_r^-1 of eq. (12) w.r.t. q.

    The error is linear in q, so this is also the map that turns the attitude
    weight of Table I into a weight on the quaternion.
    """
    pw, px, py, pz = q_conj(q_r)
    return np.array([[px, pw, pz, -py],
                     [py, -pz, pw, px],
                     [pz, py, -px, pw]])

def dynamics(x, u, drag=1.0):
    """Continuous-time dynamics, eqs. (1) to (5) and (9).

    drag scales the aerodynamic force: the simulated vehicle of Table IV is
    flown with more drag than the model of the controller assumes.
    """
    v = x[3:6]
    q = x[6:10]
    w = x[10:]
    R = q_to_rot(q)
    v_b = R.T @ v
    f_a = drag * np.array([-kd[0] * v_b[0], -kd[1] * v_b[1],
                           -kd[2] * v_b[2] + kh * (v_b[0]**2 + v_b[1]**2)])
    thrust_torque = G1 @ u
    acc = R @ (np.array([0, 0, thrust_torque[0]]) + f_a) / mass - np.array([0, 0, g])
    dq = 0.5 * q_mult(q, np.concatenate([[0.0], w]))
    dw = (thrust_torque[1:] - np.cross(w, Iv * w)) / Iv
    return np.concatenate([v, acc, dq, dw])

f = lambda x, u: dynamics(x, u)             # model used by the controller
h = lambda x, u, dt=Ts: rk4(f, x, u, dt)    # one node of the prediction

def simulate(x, u, dt=control_dt, drag=1.0):
    """Advance the simulated quadrotor by dt, holding the rotor thrusts."""
    u = np.clip(u, u_min, u_max)
    plant = lambda x, u: dynamics(x, u, drag)
    for i in range(int(round(dt / sim_dt))):
        x = rk4(plant, x, u, sim_dt)
        x[6:10] = unit_q(x[6:10])
    return x

def yaw_rotate(x, angle):
    """Rotate a state about the vertical axis.

    The model, the cost of Table I and the bounds are all invariant under this
    rotation, which is what makes a circular reference a steady state.
    """
    c, s = np.cos(angle), np.sin(angle)
    R = np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])
    q_z = np.array([np.cos(angle / 2), 0.0, 0.0, np.sin(angle / 2)])
    return np.concatenate([R @ x[:3], R @ x[3:6], q_mult(q_z, x[6:10]), x[10:]])

def circular_reference(a_max, v_max):
    """Steady state of the circular reference of eqs. (36) to (38) with n = 1.

    Returns the state and rotor thrusts of the reference at zero phase and the
    rate at which its phase advances: the reference at time t is the returned
    state rotated by yaw_rotate(., rate * t).
    """
    rate = -a_max / v_max
    period = 2 * np.pi / abs(rate)
    x_ref, u_ref = ellipse_trajectory(control_dt, a_max, v_max, 1, period)
    middle = len(u_ref) // 2
    x_bar = yaw_rotate(x_ref[middle], -rate * middle * control_dt)
    return x_bar, u_ref[middle], rate

def ellipse_trajectory(dt, a_max, v_max, n, duration, vertical=False, refine=10):
    """Reference of eqs. (36) to (38), with the states and rotor thrusts that fly it.

    The ellipse is flown at up to v_max with up to a_max of acceleration; n is
    its ellipticity. Horizontal references keep the heading pointed at the
    center of the ellipse, vertical ones keep it constant. Body rates and
    torques come from differentiating the attitude, which is done on a grid
    refine times finer than dt before sampling the reference back down.
    """
    fine = dt / refine
    r_max = v_max**2 / a_max
    r_min = r_max / n
    k = a_max / v_max
    t = np.arange(0, duration + dt, fine)
    zero = np.zeros(len(t))
    circle = np.stack([r_max * np.sin(k*t), r_min * np.cos(k*t)], axis=1)
    d_circle = np.stack([r_max * k * np.cos(k*t), -r_min * k * np.sin(k*t)], axis=1)
    dd_circle = -k**2 * circle
    if vertical:
        pos = np.stack([circle[:, 0], zero, 5 + circle[:, 1]], axis=1)
        vel = np.stack([d_circle[:, 0], zero, d_circle[:, 1]], axis=1)
        acc = np.stack([dd_circle[:, 0], zero, dd_circle[:, 1]], axis=1)
        yaw = zero
    else:
        pos = np.stack([circle[:, 0], circle[:, 1], np.full(len(t), 5.)], axis=1)
        vel = np.stack([d_circle[:, 0], d_circle[:, 1], zero], axis=1)
        acc = np.stack([dd_circle[:, 0], dd_circle[:, 1], zero], axis=1)
        yaw = np.unwrap(np.arctan2(-pos[:, 1], -pos[:, 0]))

    # Differential flatness. The drag depends on the attitude, so the thrust
    # direction and the attitude are recovered by a few fixed point iterations.
    q = np.tile(np.array([1., 0., 0., 0.]), (len(t), 1))
    thrust = mass * (acc + np.array([0, 0, g]))
    if np.min(np.linalg.norm(thrust, axis=1)) < 0.05 * mass * g:
        # Some of the slower vertical references fall freely at the top of the
        # ellipse; there the flat outputs leave the attitude undefined.
        raise ValueError("reference demands near-zero collective thrust")
    for iteration in range(200):
        previous = q.copy()
        for i in range(len(t)):
            R = q_to_rot(q[i])
            v_b = R.T @ vel[i]
            f_a = np.array([-kd[0] * v_b[0], -kd[1] * v_b[1],
                            -kd[2] * v_b[2] + kh * (v_b[0]**2 + v_b[1]**2)])
            # Under-relaxed: at high speed the drag is comparable to the
            # weight and the plain iteration oscillates.
            thrust[i] += 0.5 * (mass * (acc[i] + np.array([0, 0, g]))
                                - R @ f_a - thrust[i])
            z_b = thrust[i] / np.linalg.norm(thrust[i])
            y_c = np.array([-np.sin(yaw[i]), np.cos(yaw[i]), 0.0])
            x_b = np.cross(y_c, z_b)
            x_b /= np.linalg.norm(x_b)
            y_b = np.cross(z_b, x_b)
            q[i] = rot_to_q(np.column_stack([x_b, y_b, z_b]))
            # Keep the quaternion continuous: the heading turns by a full
            # revolution every lap, which flips the sign of the quaternion.
            if i and q[i] @ q[i - 1] < 0:
                q[i] = -q[i]
        if np.max(np.abs(q - previous)) < 1e-12:
            break
    else:
        # The drag depends on the attitude and the attitude on the drag; the
        # iteration only contracts while the collective thrust stays large.
        raise ValueError("attitude of the reference did not converge")

    rate = 2 * np.array([q_mult(q_conj(q[i]), dq)[1:] for i, dq in
                         enumerate(np.gradient(q, axis=0) / fine)])
    rate_dot = np.gradient(rate, axis=0) / fine
    tau = rate_dot * Iv + np.cross(rate, rate * Iv)
    collective = np.linalg.norm(thrust, axis=1)
    u_ref = np.linalg.solve(G1, np.column_stack([collective, tau]).T).T
    x_ref = np.hstack([pos, vel, q, rate])[::refine]
    return x_ref, u_ref[::refine][:len(x_ref) - 1]
